### PR TITLE
fix ssr

### PR DESCRIPTION
**Pull request by shiyiya**

### CODE REVIEW

**Comment by weizhenye** [comment]
In SSR, Danmaku should be marked as client code, and will never run. Is there something missed in your config?

**Comment by shiyiya** [comment]
这种自执行代码 不能静态import

**Review by weizhenye — CHANGES_REQUESTED** [review]

**Comment by shiyiya** [comment]
@weizhenye 发个版本吧？

**Comment by shiyiya** [comment]
image
@weizhenye 看起来还漏了2个地方 😭

**Pull request merged**
